name: Build HTML5

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v2
        with:
          haxe-version: 4.3.4

      - name: Configure Git for Haxelib
        run: |
          git config --global url."https://github.com/".insteadOf git@github.com:
          git config --global url."https://github.com/".insteadOf git://github.com/
          git config --global advice.detachedHead false

      - name: Install Dependencies
        run: |
          haxelib install lime --quiet
          haxelib install openfl --quiet
          haxelib install flixel --quiet
          haxelib git faxe https://github.com/as3mdf/faxe main
          haxelib run lime setup

      - name: Build Web Port
        run: haxelib run lime build html5 -final