name: Build HTML5

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v2
        with:
          haxe-version: 4.3.4

      - name: Install Dependencies
        run: |
          haxelib install lime 8.0.1 --quiet
          haxelib install openfl 9.3.2 --quiet
          haxelib install flixel 5.5.0 --quiet
          haxelib install flixel-addons 3.2.1 --quiet
          haxelib install flixel-ui 2.5.0 --quiet
          haxelib install hscript --quiet
          haxelib git faxe https://github.com/uhrobots/faxe
          haxelib run lime setup

      - name: Build Web Port
        run: haxelib run lime build html5 -final -D web